admin_role: [
  "ADMIN",
  941142369598832650
]
arc69_data: "alien_tourism_arc69.csv"
holder_data: "alien_tourism_holders.csv"
unit_name_prefix: "Tour"
name_prefix: "Alien Tourism"
image_dir: 'images'
creator_wallet: 'UWVYY2WRT7CCRPWNYUUKQ6HCO7JYTGH6TNQIJIJV6X2PG74UML2HGU5BAA'
exclude_list: [
  'UWVYY2WRT7CCRPWNYUUKQ6HCO7JYTGH6TNQIJIJV6X2PG74UML2HGU5BAA',
  'FF5K2V2RO6QP4BU2VYATQCO25EXUXUCQPNZTOVVZKEXWSY7H2RQG42QBJQ',
  'VER6JJ34CQCYVWHJHLEUUZJMNQ44QRI5UUURFTH2JCNZ5PDTXZI6YHQ7YM'
]